namespace ThisIsMassive.src.Controls
{
  partial class CBuildPartSelecter
  {
    /// <summary> 
    /// Required designer variable.
    /// </summary>
    private System.ComponentModel.IContainer components = null;

    /// <summary> 
    /// Clean up any resources being used.
    /// </summary>
    /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    protected override void Dispose(bool disposing)
    {
      if (disposing && (components != null))
      {
        components.Dispose();
      }
      base.Dispose(disposing);
    }

    #region Component Designer generated code

    /// <summary> 
    /// Required method for Designer support - do not modify 
    /// the contents of this method with the code editor.
    /// </summary>
    private void InitializeComponent()
    {
      this.components = new System.ComponentModel.Container();
      System.Windows.Forms.ListViewGroup listViewGroup1 = new System.Windows.Forms.ListViewGroup("Construction", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup2 = new System.Windows.Forms.ListViewGroup("Picture Frames", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup3 = new System.Windows.Forms.ListViewGroup("Lighting", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup4 = new System.Windows.Forms.ListViewGroup("Roads", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup5 = new System.Windows.Forms.ListViewGroup("Furniture", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup6 = new System.Windows.Forms.ListViewGroup("Misc", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup7 = new System.Windows.Forms.ListViewGroup("Shopfitting", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup8 = new System.Windows.Forms.ListViewGroup("Foliage", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewGroup listViewGroup9 = new System.Windows.Forms.ListViewGroup("Buildings", System.Windows.Forms.HorizontalAlignment.Left);
      System.Windows.Forms.ListViewItem listViewItem1 = new System.Windows.Forms.ListViewItem("Banner01", 16);
      System.Windows.Forms.ListViewItem listViewItem2 = new System.Windows.Forms.ListViewItem("Banner02", 44);
      System.Windows.Forms.ListViewItem listViewItem3 = new System.Windows.Forms.ListViewItem("Barrier01", 43);
      System.Windows.Forms.ListViewItem listViewItem4 = new System.Windows.Forms.ListViewItem("Block1x3", 19);
      System.Windows.Forms.ListViewItem listViewItem5 = new System.Windows.Forms.ListViewItem("Block3x1", 17);
      System.Windows.Forms.ListViewItem listViewItem6 = new System.Windows.Forms.ListViewItem("Book01", 18);
      System.Windows.Forms.ListViewItem listViewItem7 = new System.Windows.Forms.ListViewItem("Building01", 35);
      System.Windows.Forms.ListViewItem listViewItem8 = new System.Windows.Forms.ListViewItem("Building02", 36);
      System.Windows.Forms.ListViewItem listViewItem9 = new System.Windows.Forms.ListViewItem("Building03", 37);
      System.Windows.Forms.ListViewItem listViewItem10 = new System.Windows.Forms.ListViewItem("Ceiling", 22);
      System.Windows.Forms.ListViewItem listViewItem11 = new System.Windows.Forms.ListViewItem("CitySound", 12);
      System.Windows.Forms.ListViewItem listViewItem12 = new System.Windows.Forms.ListViewItem("Counter01", 41);
      System.Windows.Forms.ListViewItem listViewItem13 = new System.Windows.Forms.ListViewItem("Counter02", 42);
      System.Windows.Forms.ListViewItem listViewItem14 = new System.Windows.Forms.ListViewItem("Cube01", 10);
      System.Windows.Forms.ListViewItem listViewItem15 = new System.Windows.Forms.ListViewItem("Cube03", 10);
      System.Windows.Forms.ListViewItem listViewItem16 = new System.Windows.Forms.ListViewItem("Door01", 24);
      System.Windows.Forms.ListViewItem listViewItem17 = new System.Windows.Forms.ListViewItem("Doorway01", 29);
      System.Windows.Forms.ListViewItem listViewItem18 = new System.Windows.Forms.ListViewItem("Floor1x1", 22);
      System.Windows.Forms.ListViewItem listViewItem19 = new System.Windows.Forms.ListViewItem("Floor2x2", 22);
      System.Windows.Forms.ListViewItem listViewItem20 = new System.Windows.Forms.ListViewItem("Floor3x1", 47);
      System.Windows.Forms.ListViewItem listViewItem21 = new System.Windows.Forms.ListViewItem("Floor3x3", 22);
      System.Windows.Forms.ListViewItem listViewItem22 = new System.Windows.Forms.ListViewItem("FloorTri01", 23);
      System.Windows.Forms.ListViewItem listViewItem23 = new System.Windows.Forms.ListViewItem("Foundation", 8);
      System.Windows.Forms.ListViewItem listViewItem24 = new System.Windows.Forms.ListViewItem("Glass01", 27);
      System.Windows.Forms.ListViewItem listViewItem25 = new System.Windows.Forms.ListViewItem("Glass2x1", 28);
      System.Windows.Forms.ListViewItem listViewItem26 = new System.Windows.Forms.ListViewItem("Light01", 30);
      System.Windows.Forms.ListViewItem listViewItem27 = new System.Windows.Forms.ListViewItem("Light02", 31);
      System.Windows.Forms.ListViewItem listViewItem28 = new System.Windows.Forms.ListViewItem("Person01", 34);
      System.Windows.Forms.ListViewItem listViewItem29 = new System.Windows.Forms.ListViewItem("Picture03", 15);
      System.Windows.Forms.ListViewItem listViewItem30 = new System.Windows.Forms.ListViewItem("Picture04", 15);
      System.Windows.Forms.ListViewItem listViewItem31 = new System.Windows.Forms.ListViewItem("Picture05 - Screen", 38);
      System.Windows.Forms.ListViewItem listViewItem32 = new System.Windows.Forms.ListViewItem("Picture1", 6);
      System.Windows.Forms.ListViewItem listViewItem33 = new System.Windows.Forms.ListViewItem("Picture2", 5);
      System.Windows.Forms.ListViewItem listViewItem34 = new System.Windows.Forms.ListViewItem("Pillar01", 40);
      System.Windows.Forms.ListViewItem listViewItem35 = new System.Windows.Forms.ListViewItem("Pillar02", 46);
      System.Windows.Forms.ListViewItem listViewItem36 = new System.Windows.Forms.ListViewItem("Shopfront01", 25);
      System.Windows.Forms.ListViewItem listViewItem37 = new System.Windows.Forms.ListViewItem("Shopfront02", 39);
      System.Windows.Forms.ListViewItem listViewItem38 = new System.Windows.Forms.ListViewItem("Shopfront03", 45);
      System.Windows.Forms.ListViewItem listViewItem39 = new System.Windows.Forms.ListViewItem("Sphere01", 11);
      System.Windows.Forms.ListViewItem listViewItem40 = new System.Windows.Forms.ListViewItem("Stairs01", 21);
      System.Windows.Forms.ListViewItem listViewItem41 = new System.Windows.Forms.ListViewItem("straight01", 14);
      System.Windows.Forms.ListViewItem listViewItem42 = new System.Windows.Forms.ListViewItem("Table01", 13);
      System.Windows.Forms.ListViewItem listViewItem43 = new System.Windows.Forms.ListViewItem("Teleporter", 9);
      System.Windows.Forms.ListViewItem listViewItem44 = new System.Windows.Forms.ListViewItem("Tree01", 26);
      System.Windows.Forms.ListViewItem listViewItem45 = new System.Windows.Forms.ListViewItem("Tree03", 33);
      System.Windows.Forms.ListViewItem listViewItem46 = new System.Windows.Forms.ListViewItem("Wall", 0);
      System.Windows.Forms.ListViewItem listViewItem47 = new System.Windows.Forms.ListViewItem("Wall3", 0);
      System.Windows.Forms.ListViewItem listViewItem48 = new System.Windows.Forms.ListViewItem("Wedge", 20);
      System.Windows.Forms.ListViewItem listViewItem49 = new System.Windows.Forms.ListViewItem("Wedge3x1", 20);
      System.Windows.Forms.ListViewItem listViewItem50 = new System.Windows.Forms.ListViewItem("Window", 4);
      System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CBuildPartSelecter));
      this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
      this.EditPropertiesButton = new System.Windows.Forms.Button();
      this.DuplicateButton = new System.Windows.Forms.Button();
      this.PartsView = new System.Windows.Forms.ListView();
      this.imageList1 = new System.Windows.Forms.ImageList(this.components);
      this.DeleteButton = new System.Windows.Forms.Button();
      this.CanBuildHere = new System.Windows.Forms.Label();
      this.timer1 = new System.Windows.Forms.Timer(this.components);
      this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
      this.tableLayoutPanel1.SuspendLayout();
      this.SuspendLayout();
      // 
      // tableLayoutPanel1
      // 
      this.tableLayoutPanel1.BackColor = System.Drawing.Color.Gray;
      this.tableLayoutPanel1.ColumnCount = 4;
      this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
      this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
      this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
      this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
      this.tableLayoutPanel1.Controls.Add(this.EditPropertiesButton, 1, 0);
      this.tableLayoutPanel1.Controls.Add(this.DuplicateButton, 0, 0);
      this.tableLayoutPanel1.Controls.Add(this.PartsView, 0, 1);
      this.tableLayoutPanel1.Controls.Add(this.DeleteButton, 2, 0);
      this.tableLayoutPanel1.Controls.Add(this.CanBuildHere, 3, 0);
      this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
      this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
      this.tableLayoutPanel1.Name = "tableLayoutPanel1";
      this.tableLayoutPanel1.RowCount = 2;
      this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
      this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
      this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
      this.tableLayoutPanel1.Size = new System.Drawing.Size(484, 524);
      this.tableLayoutPanel1.TabIndex = 0;
      // 
      // EditPropertiesButton
      // 
      this.EditPropertiesButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(205)))), ((int)(((byte)(215)))));
      this.EditPropertiesButton.Dock = System.Windows.Forms.DockStyle.Fill;
      this.EditPropertiesButton.FlatAppearance.BorderSize = 0;
      this.EditPropertiesButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.EditPropertiesButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
      this.EditPropertiesButton.Location = new System.Drawing.Point(121, 0);
      this.EditPropertiesButton.Margin = new System.Windows.Forms.Padding(0);
      this.EditPropertiesButton.Name = "EditPropertiesButton";
      this.EditPropertiesButton.Size = new System.Drawing.Size(121, 32);
      this.EditPropertiesButton.TabIndex = 12;
      this.EditPropertiesButton.Text = "Edit";
      this.EditPropertiesButton.UseVisualStyleBackColor = false;
      this.EditPropertiesButton.Click += new System.EventHandler(this.EditPropertiesButton_Click);
      // 
      // DuplicateButton
      // 
      this.DuplicateButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
      this.DuplicateButton.Dock = System.Windows.Forms.DockStyle.Fill;
      this.DuplicateButton.FlatAppearance.BorderSize = 0;
      this.DuplicateButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.DuplicateButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
      this.DuplicateButton.Location = new System.Drawing.Point(1, 1);
      this.DuplicateButton.Margin = new System.Windows.Forms.Padding(1);
      this.DuplicateButton.Name = "DuplicateButton";
      this.DuplicateButton.Size = new System.Drawing.Size(119, 30);
      this.DuplicateButton.TabIndex = 7;
      this.DuplicateButton.Text = "Duplicate";
      this.toolTip1.SetToolTip(this.DuplicateButton, "Duplicate");
      this.DuplicateButton.UseVisualStyleBackColor = false;
      this.DuplicateButton.Click += new System.EventHandler(this.DuplicateButton_Click);
      // 
      // PartsView
      // 
      this.PartsView.BackColor = System.Drawing.Color.Gray;
      this.tableLayoutPanel1.SetColumnSpan(this.PartsView, 4);
      this.PartsView.Dock = System.Windows.Forms.DockStyle.Fill;
      this.PartsView.ForeColor = System.Drawing.Color.White;
      listViewGroup1.Header = "Construction";
      listViewGroup1.Name = "constructiongroup";
      listViewGroup2.Header = "Picture Frames";
      listViewGroup2.Name = "pictureframegroup";
      listViewGroup3.Header = "Lighting";
      listViewGroup3.Name = "LightingGroup";
      listViewGroup4.Header = "Roads";
      listViewGroup4.Name = "RoadGroup";
      listViewGroup5.Header = "Furniture";
      listViewGroup5.Name = "FurnitureGroup";
      listViewGroup6.Header = "Misc";
      listViewGroup6.Name = "MiscGroup";
      listViewGroup7.Header = "Shopfitting";
      listViewGroup7.Name = "ShopGroup";
      listViewGroup8.Header = "Foliage";
      listViewGroup8.Name = "FoliageGroup";
      listViewGroup9.Header = "Buildings";
      listViewGroup9.Name = "buildinggroup";
      this.PartsView.Groups.AddRange(new System.Windows.Forms.ListViewGroup[] {
            listViewGroup1,
            listViewGroup2,
            listViewGroup3,
            listViewGroup4,
            listViewGroup5,
            listViewGroup6,
            listViewGroup7,
            listViewGroup8,
            listViewGroup9});
      this.PartsView.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.None;
      listViewItem1.Group = listViewGroup2;
      listViewItem1.Tag = "BANNER01";
      listViewItem2.Group = listViewGroup2;
      listViewItem2.Tag = "BANNER02";
      listViewItem3.Group = listViewGroup1;
      listViewItem3.Tag = "BARRIER01";
      listViewItem4.Group = listViewGroup1;
      listViewItem4.Tag = "BLOCK1X3";
      listViewItem5.Group = listViewGroup1;
      listViewItem5.Tag = "BLOCK3X1";
      listViewItem6.Group = listViewGroup6;
      listViewItem6.Tag = "BOOK01";
      listViewItem7.Group = listViewGroup9;
      listViewItem7.Tag = "BUILDING01";
      listViewItem8.Group = listViewGroup9;
      listViewItem8.Tag = "BUILDING02";
      listViewItem9.Group = listViewGroup9;
      listViewItem9.Tag = "BUILDING03";
      listViewItem10.Group = listViewGroup1;
      listViewItem10.Tag = "CEILING01";
      listViewItem11.Group = listViewGroup6;
      listViewItem11.Tag = "AUDIOCITY01";
      listViewItem12.Group = listViewGroup7;
      listViewItem12.Tag = "COUNTER01";
      listViewItem13.Group = listViewGroup7;
      listViewItem13.Tag = "COUNTER02";
      listViewItem14.Group = listViewGroup1;
      listViewItem14.Tag = "CUBE01";
      listViewItem15.Group = listViewGroup1;
      listViewItem15.Tag = "CUBE03";
      listViewItem16.Group = listViewGroup1;
      listViewItem16.Tag = "DOOR01";
      listViewItem17.Group = listViewGroup1;
      listViewItem17.Tag = "DOORWAY01";
      listViewItem18.Group = listViewGroup1;
      listViewItem18.Tag = "FLOOR01";
      listViewItem19.Group = listViewGroup1;
      listViewItem19.Tag = "FLOOR02";
      listViewItem20.Group = listViewGroup1;
      listViewItem20.Tag = "FLOOR04";
      listViewItem21.Group = listViewGroup1;
      listViewItem21.Tag = "FLOOR03";
      listViewItem22.Group = listViewGroup1;
      listViewItem22.Tag = "FLOORTRI01";
      listViewItem23.Group = listViewGroup1;
      listViewItem23.Tag = "FOUNDATION01";
      listViewItem24.Group = listViewGroup1;
      listViewItem24.Tag = "GLASS01";
      listViewItem25.Group = listViewGroup1;
      listViewItem25.Tag = "GLASS02";
      listViewItem26.Group = listViewGroup3;
      listViewItem26.Tag = "LIGHT01";
      listViewItem27.Group = listViewGroup3;
      listViewItem27.Tag = "LIGHT02";
      listViewItem28.Group = listViewGroup7;
      listViewItem28.Tag = "PERSON01";
      listViewItem29.Group = listViewGroup2;
      listViewItem29.Tag = "PICTURE03";
      listViewItem30.Group = listViewGroup2;
      listViewItem30.Tag = "PICTURE04";
      listViewItem31.Group = listViewGroup2;
      listViewItem31.Tag = "PICTURE05";
      listViewItem32.Group = listViewGroup2;
      listViewItem32.Tag = "PICTURE01";
      listViewItem33.Group = listViewGroup2;
      listViewItem33.Tag = "PICTURE02";
      listViewItem34.Group = listViewGroup1;
      listViewItem34.Tag = "PILLAR01";
      listViewItem35.Group = listViewGroup1;
      listViewItem35.Tag = "PILLAR02";
      listViewItem36.Group = listViewGroup7;
      listViewItem36.Tag = "SHOPFRONT01";
      listViewItem37.Group = listViewGroup7;
      listViewItem37.Tag = "SHOPFRONT02";
      listViewItem38.Group = listViewGroup7;
      listViewItem38.Tag = "SHOPFRONT03";
      listViewItem39.Group = listViewGroup6;
      listViewItem39.Tag = "SPHERE01";
      listViewItem40.Group = listViewGroup1;
      listViewItem40.Tag = "STAIRS01";
      listViewItem41.Group = listViewGroup4;
      listViewItem41.Tag = "STRAIGHT01";
      listViewItem42.Group = listViewGroup5;
      listViewItem42.Tag = "TABLE01";
      listViewItem43.Group = listViewGroup6;
      listViewItem43.Tag = "TELEPORT01";
      listViewItem44.Group = listViewGroup8;
      listViewItem44.Tag = "TREE01";
      listViewItem45.Group = listViewGroup8;
      listViewItem45.Tag = "TREE03";
      listViewItem46.Group = listViewGroup1;
      listViewItem46.Tag = "WALL01";
      listViewItem47.Group = listViewGroup1;
      listViewItem47.Tag = "WALL03";
      listViewItem48.Group = listViewGroup1;
      listViewItem48.Tag = "WEDGE01";
      listViewItem49.Group = listViewGroup1;
      listViewItem49.Tag = "WEDGE3X1";
      listViewItem50.Group = listViewGroup1;
      listViewItem50.Tag = "WINDOW01";
      this.PartsView.Items.AddRange(new System.Windows.Forms.ListViewItem[] {
            listViewItem1,
            listViewItem2,
            listViewItem3,
            listViewItem4,
            listViewItem5,
            listViewItem6,
            listViewItem7,
            listViewItem8,
            listViewItem9,
            listViewItem10,
            listViewItem11,
            listViewItem12,
            listViewItem13,
            listViewItem14,
            listViewItem15,
            listViewItem16,
            listViewItem17,
            listViewItem18,
            listViewItem19,
            listViewItem20,
            listViewItem21,
            listViewItem22,
            listViewItem23,
            listViewItem24,
            listViewItem25,
            listViewItem26,
            listViewItem27,
            listViewItem28,
            listViewItem29,
            listViewItem30,
            listViewItem31,
            listViewItem32,
            listViewItem33,
            listViewItem34,
            listViewItem35,
            listViewItem36,
            listViewItem37,
            listViewItem38,
            listViewItem39,
            listViewItem40,
            listViewItem41,
            listViewItem42,
            listViewItem43,
            listViewItem44,
            listViewItem45,
            listViewItem46,
            listViewItem47,
            listViewItem48,
            listViewItem49,
            listViewItem50});
      this.PartsView.LargeImageList = this.imageList1;
      this.PartsView.Location = new System.Drawing.Point(1, 33);
      this.PartsView.Margin = new System.Windows.Forms.Padding(1);
      this.PartsView.MultiSelect = false;
      this.PartsView.Name = "PartsView";
      this.PartsView.Size = new System.Drawing.Size(482, 490);
      this.PartsView.SmallImageList = this.imageList1;
      this.PartsView.Sorting = System.Windows.Forms.SortOrder.Ascending;
      this.PartsView.TabIndex = 9;
      this.PartsView.UseCompatibleStateImageBehavior = false;
      this.PartsView.SelectedIndexChanged += new System.EventHandler(this.PartsView_SelectedIndexChanged);
      this.PartsView.MouseClick += new System.Windows.Forms.MouseEventHandler(this.PartsView_MouseClick);
      // 
      // imageList1
      // 
      this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
      this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
      this.imageList1.Images.SetKeyName(0, "icons8-brick-wall-16.png");
      this.imageList1.Images.SetKeyName(1, "icons8-door-40.png");
      this.imageList1.Images.SetKeyName(2, "icons8-wooden-floor-64.png");
      this.imageList1.Images.SetKeyName(3, "icons8-roofing-64.png");
      this.imageList1.Images.SetKeyName(4, "icons8-open-window-16.png");
      this.imageList1.Images.SetKeyName(5, "icons8-picture-64.png");
      this.imageList1.Images.SetKeyName(6, "icons8-xlarge-icons-64.png");
      this.imageList1.Images.SetKeyName(7, "icons8-light-on-64.png");
      this.imageList1.Images.SetKeyName(8, "icons8-home-64.png");
      this.imageList1.Images.SetKeyName(9, "icons8-communicator-30.png");
      this.imageList1.Images.SetKeyName(10, "icons8-sugar-cube-40.png");
      this.imageList1.Images.SetKeyName(11, "icons8-beach-ball-40.png");
      this.imageList1.Images.SetKeyName(12, "icons8-octahedron-80.png");
      this.imageList1.Images.SetKeyName(13, "table01.png");
      this.imageList1.Images.SetKeyName(14, "straight01.png");
      this.imageList1.Images.SetKeyName(15, "picture03.png");
      this.imageList1.Images.SetKeyName(16, "banner01.png");
      this.imageList1.Images.SetKeyName(17, "block3x1.png");
      this.imageList1.Images.SetKeyName(18, "book01.png");
      this.imageList1.Images.SetKeyName(19, "block1x3.png");
      this.imageList1.Images.SetKeyName(20, "wedge3x1.png");
      this.imageList1.Images.SetKeyName(21, "stairs01.png");
      this.imageList1.Images.SetKeyName(22, "floor01.png");
      this.imageList1.Images.SetKeyName(23, "floortri01.png");
      this.imageList1.Images.SetKeyName(24, "door01.png");
      this.imageList1.Images.SetKeyName(25, "shopfront01.png");
      this.imageList1.Images.SetKeyName(26, "fir01.png");
      this.imageList1.Images.SetKeyName(27, "glass01.png");
      this.imageList1.Images.SetKeyName(28, "glass02.png");
      this.imageList1.Images.SetKeyName(29, "doorway01.png");
      this.imageList1.Images.SetKeyName(30, "sphere01.png");
      this.imageList1.Images.SetKeyName(31, "light02.png");
      this.imageList1.Images.SetKeyName(32, "tree02.png");
      this.imageList1.Images.SetKeyName(33, "tree03.png");
      this.imageList1.Images.SetKeyName(34, "person01.png");
      this.imageList1.Images.SetKeyName(35, "building01.png");
      this.imageList1.Images.SetKeyName(36, "building02.png");
      this.imageList1.Images.SetKeyName(37, "building03.png");
      this.imageList1.Images.SetKeyName(38, "picture05.png");
      this.imageList1.Images.SetKeyName(39, "shopfront02.png");
      this.imageList1.Images.SetKeyName(40, "pillar01.png");
      this.imageList1.Images.SetKeyName(41, "counter01.png");
      this.imageList1.Images.SetKeyName(42, "counter02.png");
      this.imageList1.Images.SetKeyName(43, "barrier01.png");
      this.imageList1.Images.SetKeyName(44, "banner01.png");
      this.imageList1.Images.SetKeyName(45, "shopfront03.png");
      this.imageList1.Images.SetKeyName(46, "pillar02.png");
      this.imageList1.Images.SetKeyName(47, "floor3x1.png");
      // 
      // DeleteButton
      // 
      this.DeleteButton.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
      this.DeleteButton.Dock = System.Windows.Forms.DockStyle.Fill;
      this.DeleteButton.FlatAppearance.BorderSize = 0;
      this.DeleteButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.DeleteButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
      this.DeleteButton.Location = new System.Drawing.Point(242, 0);
      this.DeleteButton.Margin = new System.Windows.Forms.Padding(0);
      this.DeleteButton.Name = "DeleteButton";
      this.DeleteButton.Size = new System.Drawing.Size(121, 32);
      this.DeleteButton.TabIndex = 10;
      this.DeleteButton.Text = "Delete";
      this.toolTip1.SetToolTip(this.DeleteButton, "Delete");
      this.DeleteButton.UseVisualStyleBackColor = false;
      this.DeleteButton.Click += new System.EventHandler(this.DeleteButton_Click);
      // 
      // CanBuildHere
      // 
      this.CanBuildHere.AutoSize = true;
      this.CanBuildHere.Dock = System.Windows.Forms.DockStyle.Fill;
      this.CanBuildHere.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
      this.CanBuildHere.Font = new System.Drawing.Font("Microsoft Sans Serif", 6.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
      this.CanBuildHere.Location = new System.Drawing.Point(366, 0);
      this.CanBuildHere.Name = "CanBuildHere";
      this.CanBuildHere.Size = new System.Drawing.Size(115, 32);
      this.CanBuildHere.TabIndex = 13;
      this.CanBuildHere.Text = "Zone Unlocked";
      this.CanBuildHere.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
      this.toolTip1.SetToolTip(this.CanBuildHere, "Shows current build availability in this region.");
      // 
      // timer1
      // 
      this.timer1.Interval = 500;
      this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
      // 
      // CBuildPartSelecter
      // 
      this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
      this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
      this.Controls.Add(this.tableLayoutPanel1);
      this.Margin = new System.Windows.Forms.Padding(0);
      this.Name = "CBuildPartSelecter";
      this.Size = new System.Drawing.Size(484, 524);
      this.VisibleChanged += new System.EventHandler(this.CBuildPartSelecter_VisibleChanged);
      this.tableLayoutPanel1.ResumeLayout(false);
      this.tableLayoutPanel1.PerformLayout();
      this.ResumeLayout(false);

    }

    #endregion

    private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
    private System.Windows.Forms.Button DuplicateButton;
    private System.Windows.Forms.ListView PartsView;
    private System.Windows.Forms.ImageList imageList1;
    private System.Windows.Forms.Button DeleteButton;
    private System.Windows.Forms.Button EditPropertiesButton;
    private System.Windows.Forms.Label CanBuildHere;
    private System.Windows.Forms.Timer timer1;
    private System.Windows.Forms.ToolTip toolTip1;
  }
}
